version: '3'
services:
  keycloak:
    image: jboss/keycloak 
    restart: always
    expose:
      - "8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
  reverseproxy:
    bild: ./sample-app
