version: '3'
services:
  keycloak:
    image: jboss/keycloak 
    restart: always
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
  rp:
    build: ./sample-app
    ports:
      - "8081:8081"
